---
- name: include aws keys
  include_vars: secrets.yml
  no_log: true

- name: deploy logstash configuration
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: root
    mode: '0644'

- name: restart logstash
  ansible.builtin.systemd_service:
    name: logstash
    state: restarted
