---
- name: check if ant binary exists
  ansible.builtin.stat:
    path: "{{ binary_dir }}/ant"
  register: ant_binary

- name: download the ant binary
  ansible.builtin.get_url:
    url: "{{ ant_archive_url }}"
    dest: "/tmp/{{ ant_archive_filename }}"
  when: not ant_binary.stat.exists

- name: extract the ant binary to /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ ant_archive_filename }}"
    dest: "{{ binary_dir }}"
    remote_src: true
  become: true
  when: not ant_binary.stat.exists

- name: create ant users
  ansible.builtin.user:
    name: "ant{{ item }}"
    shell: /bin/bash
    state: present
  loop: "{{ range(1, ant_uploader_instances | int + 1) | list }}"

- name: copy upload-random-data.sh to remote for each ant user
  ansible.builtin.template:
    src: upload-random-data.sh.j2
    dest: "/home/ant{{ item }}/upload-random-data.sh"
    owner: "ant{{ item }}"
    group: "ant{{ item }}"
    mode: '0744'
  become: true
  become_user: "ant{{ item }}"
  loop: "{{ range(1, ant_uploader_instances | int + 1) | list }}"

- name: Check if systemd service file exists
  ansible.builtin.stat:
    path: "/etc/systemd/system/ant_uploader_{{ item }}.service"
  register: service_file_stat
  loop: "{{ range(1, ant_uploader_instances | int + 1) | list }}"

- name: Retrieve secret keys
  set_fact:
    secret_keys_per_machine: "{{ ant_secret_key_map[inventory_hostname] | regex_replace('\"', '') }}"

- name: create systemd service file
  ansible.builtin.template:
    src: ant_uploader.service.j2
    dest: "/etc/systemd/system/ant_uploader_{{ item.0 }}.service"
    owner: "ant{{ item.0 }}"
    group: "ant{{ item.0 }}"
    mode: '0644'
  become: true
  when: not service_file_stat.results[item.0 - 1].stat.exists
  loop: "{{ range(1, ant_uploader_instances | int + 1) | zip(secret_keys_per_machine) }}"
  vars: 
    count: "{{ item.0 }}"
    secret_key: "{{ item.1 }}"

- name: start and enable ant_uploader service for each uploader
  ansible.builtin.systemd:
    name: "ant_uploader_{{ item }}"
    state: started
    enabled: yes
  become: true
  loop: "{{ range(1, ant_uploader_instances | int + 1) | list }}"
