---
- name: store s3_deploy secret access key
  set_fact:
    aws_secret_key: "{{ lookup('file', 'files/s3_deploy_secret_access_key') }}"

- name: clone safe_network repo
  ansible.builtin.git:
    repo: https://github.com/{{ org }}/safe_network
    version: "{{ branch }}"
    dest: "{{ ansible_env.HOME }}/safe_network"

- name: build safenode
  ansible.builtin.shell: |
    source $HOME/.cargo/env
    cargo build --target x86_64-unknown-linux-musl --release --bin safenode
  args:
    chdir: "{{ ansible_env.HOME }}/safe_network"
    creates: "{{ ansible_env.HOME }}/safe_network/target/x86_64-unknown-linux-musl/release/safenode"
    executable: /bin/bash

- name: copy safenode binary to tmp directory
  ansible.builtin.command:
    chdir: "{{ ansible_env.HOME }}/safe_network/target/x86_64-unknown-linux-musl/release"
    cmd: cp safenode /tmp/

- name: archive binary
  ansible.builtin.command:
    chdir: /tmp/
    cmd: tar -zcvf {{ node_archive_filename }} safenode

- name: upload safenode archive to S3
  amazon.aws.s3_object:
    access_key: AKIAVVODCRMSELAPBQHK
    secret_key: "{{ aws_secret_key }}"
    bucket: sn-node
    object: /{{ org }}/{{ branch }}/{{ node_archive_filename }}
    src: /tmp/{{ node_archive_filename }}
    mode: put
    permission: public-read
