---
- name: import elasticsearch gpg key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Install required packages
  apt:
    name: apt-transport-https
    state: present

- name: add elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat
    state: present
    update_cache: yes
  register: result
  until: result is succeeded
  retries: 10
  delay: 10

# This file will have been copied to the machine from the controller.
- name: copy logstash-public.crt
  copy:
    src: /tmp/logstash-{{ logstash_stack_name }}-public.crt
    dest: "{{ ssl_public_certs_path }}/logstash-public.crt"
    remote_src: yes
    mode: 0644

- name: copy filebeat configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644

- name: enable and start filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started
