---
- name: update apt cache
  apt:
    update_cache: yes

# The retries are for random lock failures.
- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - heaptrack
    - python3
    - python3-pip
    - ripgrep
    - zip
    - jq
  register: result
  until: result is succeeded
  retries: 20
  delay: 10

- name: install boto3
  ansible.builtin.command: pip3 install boto3 --prefix /usr
