---
- name: start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: find the json file in the bootstrap cache directory
  find:
    paths: "{{ bootstrap_cache_dir }}"
    patterns: "*.json"
  register: json_files

- name: fail if no json file is found
  fail:
    msg: "No json file found in the bootstrap directory."
  when: json_files.matched == 0

- name: ensure nginx is serving the json file using a template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  when: json_files.matched > 0

- name: ensure nginx status site file is set
  template:
    src: nginx_status.conf.j2
    dest: /etc/nginx/sites-available/nginx_status

- name: ensure nginx status file symlink is present
  file:
    src: /etc/nginx/sites-available/nginx_status
    dest: /etc/nginx/sites-enabled/nginx_status
    state: link
  when: json_files.matched > 0

- name: reload nginx to apply changes
  service:
    name: nginx
    state: reloaded
  when: json_files.matched > 0
