---
# We always build the faucet binary, but safenode only applies for using a custom branch.
- name: build binaries
  hosts: all
  become: False
  roles:
    - {
        role: build_safe_network_binary,
        bin_name: "faucet"
      }
    - {
        role: build_safe_network_binary,
        bin_name: "safe"
      }
    - {
        role: build_safe_network_binary,
        bin_name: "safenode",
        when: custom_safenode == "true"
      }
