---
- name: build binaries
  hosts: all
  become: False
  roles:
    - {
        role: build_safe_network_binary,
        bin_name: "ant",
        when: custom_bin == "true"
      }
    - {
        role: build_safe_network_binary,
        bin_name: "antnode",
        when: custom_bin == "true"
      }
    - {
        role: build_safe_network_binary,
        bin_name: "antctl",
        when: custom_bin == "true"
      }
    - {
        role: build_safe_network_binary,
        bin_name: "antctld",
        when: custom_bin == "true"
      }
