---
- name: build a custom node image
  hosts: all
  become: True
  roles:
    - role: prerequisites
  # Right now we are in a situation where we don't want Telegraf to be started automatically because
  # we don't want metrics with new names to be forwarded to the existing production infrastructure.
  tasks:
    - name: stop telegraf
      become: True
      ansible.builtin.systemd:
        name: telegraf
        state: stopped
        enabled: no
