---
- name: deploy evm nodes
  hosts: all
  become: True
  max_fail_percentage: 10
  ignore_unreachable: yes
  roles:
    - safe_user
    - evm_node
  tasks:
    # Something is wrong with the journal service on Ubuntu that causes no
    # output to be produced when running `journalctl`. The solution seemed
    # to be restarting the service.
    - name: restart systemd-journald
      become: True
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted
        enabled: yes