---
- name: deploy antnode to genesis node
  hosts: all
  become: False
  vars:
    is_genesis: True
  roles:
    - role: ant_user
      become: True
    - role: setup_striped_storage
      become: True
    - antctl
    - genesis-node
    - role: cache_webserver
      become: True
