---
- name: deploy antnode to peer cache nodes
  hosts: all
  become: False
  max_fail_percentage: 10
  ignore_unreachable: yes
  vars:
    is_genesis: False
  roles:
    - role: ant_user
      become: True
    - role: attach_volume
      become: True
    - {
        role: format_disk,
        become: True,
        block_device: "{{ block_device }}",
        mount_info:
          { name: "{{ node_data_mount_path }}", owner: "root", group: "root", mode: 0755 },
        when: provider == "aws"
      }
    - antctl
    - role: telegraf-configuration
      become: True
    - role: telegraf-geoip
      become: True
    - node
    - role: cache_webserver
      become: True

  tasks:
    # Something is wrong with the journal service on Ubuntu that causes no
    # output to be produced when running `journalctl`. The solution seemed
    # to be restarting the service.
    - name: restart systemd-journald
      become: True
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted
        enabled: yes
    - name: restart telegraf
      become: True
      ansible.builtin.systemd:
        name: telegraf
        state: restarted
        enabled: yes
      when: enable_telegraf | bool
