---
- name: ensure the ant uploader service is started
  hosts: all
  become: True
  tasks:
    - name: get list of ant users
      ansible.builtin.shell: "getent passwd | grep '^ant[0-9]\\+:' | cut -d: -f1"
      register: ant_users
      changed_when: false

    - name: start all ant uploader services
      ansible.builtin.systemd:
        name: "ant_uploader_{{ item | regex_replace('ant([0-9]+)', '\\1') }}"
        state: started
        enabled: yes
      become: true
      loop: "{{ ant_users.stdout_lines }}"
