---
- name: ensure all nodes are started using the node manager
  hosts: all
  become: True
  vars:
    interval: "{{ interval }}"
  tasks:
    - name: start
      ansible.builtin.command: "antctl start --interval {{ interval }}"
