---
- name: ensure ant uploader services are started
  hosts: all
  become: True
  tasks:
    - name: start all uploader services
      ansible.builtin.systemd:
        name: "ant_uploader_{{ item }}"
        state: started
        enabled: yes
      become: true
      loop: "{{ range(1, ant_uploader_instances | int + 1) | list }}"
