---
- name: upgrade the uploaders
  hosts: all
  become: True
  vars:
    autonomi_version: "{{ autonomi_version }}"
    autonomi_archive_url: "https://autonomi-cli.s3.eu-west-2.amazonaws.com/autonomi-{{ autonomi_version }}-x86_64-unknown-linux-musl.tar.gz"
  tasks:
    - name: get list of safe users
      ansible.builtin.shell: "getent passwd | grep '^safe[0-9]\\+:' | cut -d: -f1"
      register: safe_users
      changed_when: false

    - name: stop all uploader services
      systemd:
        name: "autonomi_uploader_{{ item | regex_replace('safe([0-9]+)', '\\1') }}"
        state: stopped
      loop: "{{ safe_users.stdout_lines }}"

    # It is safer to make sure both of these are removed, because Ansible may not re-download and
    # replace them if they already exist.
    - name: remove existing autonomi binary
      ansible.builtin.file:
        path: /usr/local/bin/autonomi
        state: absent

    - name: remove existing autonomi archive
      ansible.builtin.file:
        path: /tmp/autonomi-latest-x86_64-unknown-linux-musl.tar.gz
        state: absent

    - name: download the new autonomi binary
      ansible.builtin.get_url:
        url: "{{ autonomi_archive_url }}"
        dest: /tmp/autonomi-latest-x86_64-unknown-linux-musl.tar.gz

    - name: extract the new autonomi binary
      ansible.builtin.unarchive:
        src: /tmp/autonomi-latest-x86_64-unknown-linux-musl.tar.gz
        dest: /usr/local/bin
        remote_src: True

    - name: copy upload-random-data.sh to remote for each safe user
      ansible.builtin.template:
        src: roles/uploaders/templates/upload-random-data.sh.j2
        dest: "/home/safe{{ item | regex_replace('safe([0-9]+)', '\\1') }}/upload-random-data.sh"
        owner: "safe{{ item | regex_replace('safe([0-9]+)', '\\1') }}"
        group: "safe{{ item | regex_replace('safe([0-9]+)', '\\1') }}"
        mode: '0744'
      become_user: "safe{{ item | regex_replace('safe([0-9]+)', '\\1') }}"
      loop: "{{ safe_users.stdout_lines }}"

    - name: start all uploader services
      systemd:
        name: "autonomi_uploader_{{ item | regex_replace('safe([0-9]+)', '\\1') }}"
        state: started
        enabled: true
      loop: "{{ safe_users.stdout_lines }}"