---
- name: upgrade the client telegraf configuration
  hosts: all
  roles:
    - role: telegraf-client
      become: True
  tasks:
    - name: restart telegraf service
      systemd:
        name: telegraf
        enabled: yes
        state: restarted