---
- name: upgrade the ANT binary
  hosts: all
  become: True
  vars:
    ant_archive_url: "https://autonomi-cli.s3.eu-west-2.amazonaws.com/ant-{{ ant_version }}-x86_64-unknown-linux-musl.tar.gz"
    log_output_dest: /mnt/client-logs/log/uploads
  tasks:
    - name: get list of ant users
      ansible.builtin.shell: "getent passwd | grep '^ant[0-9]\\+:' | cut -d: -f1"
      register: ant_users
      changed_when: false

    - name: stop all ANT uploader services
      systemd:
        name: "ant_random_uploader_{{ item | regex_replace('ant([0-9]+)', '\\1') }}"
        state: stopped
      loop: "{{ ant_users.stdout_lines }}"

    - name: stop all ANT downloader services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - ant_download_verifier
        - ant_download_random_verifier
        - ant_performance_verifier

    # It is antr to make sure both of these are removed, because Ansible may not re-download and
    # replace them if they already exist.
    - name: remove existing ANT binary
      ansible.builtin.file:
        path: /usr/local/bin/ant
        state: absent

    - name: remove existing ant archive
      ansible.builtin.file:
        path: /tmp/ant-latest-x86_64-unknown-linux-musl.tar.gz
        state: absent

    - name: download the new ant binary
      ansible.builtin.get_url:
        url: "{{ ant_archive_url }}"
        dest: /tmp/ant-latest-x86_64-unknown-linux-musl.tar.gz

    - name: extract the new ant binary
      ansible.builtin.unarchive:
        src: /tmp/ant-latest-x86_64-unknown-linux-musl.tar.gz
        dest: /usr/local/bin
        remote_src: True

    - name: copy ant_random_uploader.sh to remote for each ant user
      ansible.builtin.template:
        src: roles/uploaders/templates/ant_random_uploader.sh.j2
        dest: "/home/ant{{ item | regex_replace('ant([0-9]+)', '\\1') }}/ant_random_uploader.sh"
        owner: "ant{{ item | regex_replace('ant([0-9]+)', '\\1') }}"
        group: "ant"
        mode: '0744'
      become_user: "ant{{ item | regex_replace('ant([0-9]+)', '\\1') }}"
      loop: "{{ ant_users.stdout_lines }}"

    - name: copy ant_downloader.sh to remote
      ansible.builtin.template:
        src: ant_downloader.sh.j2
        dest: /home/ant1/ant_downloader.sh
        owner: ant1
        group: ant
        mode: '0775'
      become: true
      become_user: ant1

    - name: start all ANT uploader services
      systemd:
        name: "ant_random_uploader_{{ item | regex_replace('ant([0-9]+)', '\\1') }}"
        state: started
        enabled: true
      loop: "{{ ant_users.stdout_lines }}"

    - name: start all ANT downloader services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - ant_download_verifier
        - ant_download_random_verifier
        - ant_performance_verifier
