---
- name: upgrade antctl to a new version
  hosts: all
  become: False
  max_fail_percentage: 10
  ignore_unreachable: yes
  vars:
    antctl_archive_filename: antctl-{{ version }}-x86_64-unknown-linux-musl.tar.gz
    antctl_archive_url: https://antctl.s3.eu-west-2.amazonaws.com/{{ antctl_archive_filename }}
  tasks:
    - name: download the antctl binary
      ansible.builtin.get_url:
        url: "{{ antctl_archive_url }}"
        dest: /tmp/{{ antctl_archive_filename }}
    - name: extract the antctl binary to /usr/local/bin
      become: True
      ansible.builtin.unarchive:
        src: "/tmp/{{ antctl_archive_filename }}"
        dest: "/usr/local/bin"
        remote_src: True