---
- name: upgrade node binaries using the node manager
  hosts: all
  tasks:
    # There is an optional delay that can be applied before the upgrade starts.
    # This is useful for when there is one node per machine.
    - name: upgrade nodes
      ansible.builtin.shell: |
        {% if pre_upgrade_delay is defined %}
        sleep {{ pre_upgrade_delay | default(0) }}
        {% endif %}
        cmd="safenode-manager upgrade --interval={{ interval }}"
        {% if force_safenode is defined %}
        cmd="$cmd --force"
        {% endif %}
        {% if env_variables is defined %}
        cmd="$cmd --env={{ env_variables }}"
        {% endif %}
        {% if safenode_version is defined %}
        cmd="$cmd --version={{ safenode_version }}"
        {% endif %}
        eval "$cmd"
      args:
        executable: /bin/bash