---
- name: upgrade the node telegraf configuration
  hosts: all
  roles:
    - role: telegraf-node
      become: True
  tasks:
    - name: restart telegraf service
      ansible.builtin.systemd:
        name: telegraf
        enabled: yes
        state: restarted