---
org: maidsafe
branch: main
# If a custom branch is specified, the URL must be changed to
# "https://sn-node.s3.eu-west-2.amazonaws.com/{org}/{branch}/{bin_name}-{testnet_name}-x86_64-unknown-linux-musl.tar.gz"
# Currently it is done directly inside the code
antnode_rpc_client_archive_filename: antnode_rpc_client-latest-x86_64-unknown-linux-musl.tar.gz
antnode_rpc_client_archive_url: https://antnode-rpc-client.s3.eu-west-2.amazonaws.com/{{ antnode_rpc_client_archive_filename }}
antnode_rpc_client_archive_dest_path: /usr/local/bin
royalties_cash_notes_dir_path: /mnt/antnode-storage/log/antnode/royalties-cash-notes
